export const AUTH = 'AUTH';

export const BASE_GET_REQUEST = 'BASE_GET_REQUEST';

export const FILTER_LIST = 'FILTER_LIST';

export const BASE_POST_REQUEST = 'BASE_POST_REQUEST';

export const BASE_PUT_REQUEST = 'BASE_PUT_REQUEST';

export const UPDATE_USER_SETTINGS_SAGA = 'UPDATE_USER_SETTINGS_SAGA';

export const BASE_DELETE_REQUEST = 'BASE_DELETE_REQUEST';

export const UPDATE_USER_DATA_SAGA = 'UPDATE_USER_DATA_SAGA';

export const BLOCK_USER_REQUEST = 'BLOCK_USER_REQUEST';

export const BASE_GET_REQUEST_USERS = 'BASE_GET_REQUEST_USERS';